### ISSUE TITLE
Hello, wanna become a member))

### ISSUE THREAD

**Issue by liashchynskyi** [shitjs/meta#3]

**Comment by liashchynskyi** [comment]
@vyorkin 👋

**Comment by vyorkin** [comment]
hey, @liashchynskyi 
I'm kinda guest here too so it is better to ping someone from the core team 😆

**Comment by liashchynskyi** [comment]
@vyorkin could you tell me one of them? :smile:

**Comment by vyorkin** [comment]
sure, feel free to ping anyone from the org: https://github.com/orgs/shitjs/people

**Comment by liashchynskyi** [comment]
I know, but the problem is I don't know who of them is the admin :rofl:

**Comment by terrysahaidak** [comment]
@chicoxyzzy ^

**Comment by chicoxyzzy** [comment]
✅
